name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Set environment variables
        run: |
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "GOROOT=/usr/local/go" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test
